import type { DashboardRow } from '@/lib/assessment-builder-dashboard';

/** Static seed rows aligned with public/prototypes/sei-assessment-builder-v8.html PROJECTS (prototype filename unchanged). */
export const ASSESSMENT_BUILDER_SEED_ROWS: DashboardRow[] = [
  {
    id: 'seed-meridian',
    clientName: 'Meridian Financial Group',
    stakeholdersDisplay: 'Dana Reyes, Tom Archuleta, Sarah Kim',
    statusLabel: 'Discovery',
    statusBadgeClass: 'b-disc',
    dotClass: 'd-live',
    docCount: 2,
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'seed-clearwater',
    clientName: 'Clearwater Health Systems',
    stakeholdersDisplay: 'Kevin Marsh, Lisa Chen',
    statusLabel: 'Draft Ready',
    statusBadgeClass: 'b-draft',
    dotClass: 'd-draft',
    docCount: 3,
    updatedAt: new Date('2026-03-14T14:22:00'),
  },
  {
    id: 'seed-oakhurst',
    clientName: 'Oakhurst Logistics',
    stakeholdersDisplay: 'James Ford, Priya Nair',
    statusLabel: 'Complete',
    statusBadgeClass: 'b-done',
    dotClass: 'd-done',
    docCount: 4,
    updatedAt: new Date('2026-02-28T10:05:00'),
  },
  {
    id: 'seed-vantage',
    clientName: 'Vantage Capital Partners',
    stakeholdersDisplay: 'Rachel Soto',
    statusLabel: 'Draft Ready',
    statusBadgeClass: 'b-draft',
    dotClass: 'd-draft',
    docCount: 1,
    updatedAt: new Date('2026-03-10T09:40:00'),
  },
  {
    id: 'seed-skybridge',
    clientName: 'SkyBridge Technologies',
    stakeholdersDisplay: 'Omar Hasan, Tanya Lee, Will Park',
    statusLabel: 'Discovery',
    statusBadgeClass: 'b-disc',
    dotClass: 'd-live',
    docCount: 2,
    updatedAt: new Date('2026-03-19T16:10:00'),
  },
  {
    id: 'seed-redwood',
    clientName: 'Redwood Municipal Services',
    stakeholdersDisplay: 'Carol Bates',
    statusLabel: 'Complete',
    statusBadgeClass: 'b-done',
    dotClass: 'd-done',
    docCount: 5,
    updatedAt: new Date('2026-02-12T11:30:00'),
  },
];
